"""Bilingual, progressively enhanced pages. The prose is not generated at runtime."""
from html import escape as e
import re
REPO='https://github.com/spicmaff/malonaldehyde-transition-sampling'
SECTIONS=['overview','molecule','sampling','landscape','seeds','applicability','train119','story','longread','reproduce']

def molecule_svg(xyz):
    p=[(62+(x-6.35)*109,366-(y-6.3)*83) for x,y,z in xyz]
    bonds=[(0,2),(2,3),(2,4),(4,5),(4,6),(6,7),(6,8)]
    s='<svg viewBox="0 0 560 390" role="img" aria-label="Malonaldehyde: nine atoms on the saved PBE path"><title>Malonaldehyde, saved central NEB geometry</title>'
    for i,j in bonds+[(0,1),(1,7)]:
        dash=' stroke-dasharray="5 6"' if 1 in (i,j) else ''
        s+=f'<line x1="{p[i][0]}" y1="{p[i][1]}" x2="{p[j][0]}" y2="{p[j][1]}" stroke="currentColor" opacity=".45" stroke-width="3"{dash}/>'
    for i,(x,y) in enumerate(p):
        color='var(--oxygen)' if i in (0,7) else 'var(--targeted)' if i==1 else 'var(--carbon)' if i in (2,4,6) else 'var(--hydrogen)'
        r=18 if i in (0,7) else 13 if i==1 else 16 if i in (2,4,6) else 10
        s+=f'<circle cx="{x}" cy="{y}" r="{r}" fill="{color}" stroke="var(--panel)" stroke-width="2"/>'
        if i in (0,1,7):s+=f'<text x="{x}" y="{y+36}" text-anchor="middle" fill="var(--ink)" font-size="15">'+('H*' if i==1 else 'O')+'</text>'
    return s+'</svg>'

def render(lang,d,article):
    ru=lang=='ru'; t=lambda en,ru_:ru_ if ru else en
    names=t(['Overview','Molecule','Sampling','Energy landscape','Five seeds','Applicability','Train119','Films','Longread','Reproduce'],['Обзор','Молекула','Выборка','Энергия','Пять seeds','Применимость','Train119','Видео','Лонгрид','Воспроизвести'])
    def source(*keys):
        links=''.join(f'<li><a href="{d["evidence"][k]["url"]}">{e(d["evidence"][k]["path"])}</a><small>SHA-256 {d["evidence"][k]["sha256"]}</small></li>' for k in keys)
        return f'<details class="source"><summary>{t("Evidence & source files","Доказательства и источники")}</summary><ul>{links}</ul></details>'
    def head(n,eyebrow,title,lead):return f'<div class="page-head"><p class="eyebrow"><span>{n:02d}</span> / {eyebrow}</p><h1 id="title-{SECTIONS[n]}">{title}</h1><p class="lede">{lead}</p></div>'
    def sec(id,body):return f'<section class="page" id="{id}" aria-labelledby="title-{id}">{body}</section>'
    def note(s):return f'<aside class="note">{s}</aside>'
    def table(headers,rows,caption):return '<div class="table-wrap"><table><caption>'+caption+'</caption><thead><tr>'+''.join(f'<th scope="col">{x}</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join(f'<td>{x}</td>' for x in r)+'</tr>' for r in rows)+'</tbody></table></div>'
    def fallback(headers,rows,caption):return '<details class="values"><summary>'+t('Read the numerical table','Открыть численную таблицу')+'</summary>'+table(headers,rows,caption)+'</details>'
    def pill(s,cl=''):return f'<span class="badge {cl}">{s}</span>'
    def nextlink(id,title):return f'<a class="next-link" href="#{id}">{title}<span aria-hidden="true">↗</span></a>'
    def chart(id):return f'<div class="chart" id="{id}"><p class="js-only loading">{t("Loading the verified data…","Загрузка проверенных данных…")}</p></div>'
    main=[]
    # 00 — overview
    overview=f'''<div class="hero"><div class="hero-copy"><p class="eyebrow">DFT · MTP · {t('A research story','История исследования')}</p><h1 id="title-overview">{t('One proton.<br>Two ways<br>to <em>learn.</em>','Один протон.<br>Два способа<br><em>обучения.</em>')}</h1><p class="lede">{t('A small molecule asks a difficult question: where should a machine potential learn—and when should we trust it?','Маленькая молекула задаёт непростой вопрос: где обучать машинный потенциал — и когда ему доверять?')}</p><p class="byline">{t('Mikhail Fofonov','Михаил Фофонов')} <span>·</span> {t('Malonaldehyde / computational chemistry','Малональдегид / вычислительная химия')}</p><div class="actions"><a class="button primary" href="#molecule">{t('Explore the molecule','Исследовать молекулу')} <span>↗</span></a><a class="text-link" href="#longread">{t('Read the story','Читать историю')} →</a></div></div><figure class="hero-visual"><div class="figure-meta"><span>C₃H₄O₂</span><span>{t('Saved PBE path','Сохранённый PBE-путь')}</span></div><div id="hero-molecule">{molecule_svg(d['molecule'][4]['xyz'])}</div><div class="hero-coordinate"><span>O—H* ··· O</span><strong id="hero-q">q<sub>PT</sub> ≈ 0 Å</strong></div><label class="js-only slider-label" for="hero-scrub">{t('Move the proton along the path','Переместите протон вдоль пути')}<input id="hero-scrub" type="range" min="0" max="8" step="1" value="4"></label><figcaption>{t('Nine computed geometries, not a movie of a reaction. Explore the saved images; animation is display interpolation, never physical time.','Девять рассчитанных геометрий, а не запись реакции. Анимация — визуальная интерполяция; её время не физическое.')}</figcaption></figure></div>
    <div class="research-spine"><div class="section-bar"><h2>{t('The story, in four observations','История в четырёх наблюдениях')}</h2><span class="small">{t('Results and limits belong together.','Результат и его границы — вместе.')}</span></div><div class="spine-grid">'''
    cards=[('36 + 24',t('Same budget. Different places.','Один бюджет. Разные области.'),t('Both original models learn from 60 DFT configurations. Placement, not a larger budget, changes.','Обе исходные модели обучены на 60 конфигурациях DFT. Меняется размещение данных, не их число.'),'sampling',t('Locked comparison','Фиксированное сравнение')),
           (t('35.25 → 4.10','35,25 → 4,10'),t('A much smaller barrier error.','Ошибка барьера заметно меньше.'),t('meV, for the original saved model pair—not a promise for every training run.','meV, для исходной сохранённой пары — не обещание для каждого обучения.'),'landscape',t('Original pair','Исходная пара')),
           ('3 / 5',t('Randomness changes the story.','Случайность меняет вывод.'),t('Paired seeds where targeted wins both metrics. The ordering is seed-sensitive.','Пар seeds, где targeted лучше по обеим метрикам. Результат чувствителен к инициализации.'),'seeds','SEED_SENSITIVE'),
           ('11 / 11',t('Local accuracy, not deployment.','Локальная точность, не готовность.'),t('Later Train119 checks satisfy A2 locally. Its frozen applicability failure still stands.','Поздние проверки Train119 проходят A2 локально. Отказ по применимости сохраняется.'),'train119',t('Development diagnostic','Диагностика разработки'))]
    for number,title,desc,route,badge in cards:overview+=f'<article class="spine-item">{pill(badge)}<div class="number">{number}</div><h3>{title}</h3><p>{desc}</p><a href="#{route}">{t("Explore","Подробнее")} →</a></article>'
    overview+='</div></div>'+source('methods','path','seeds','diagnostic')+note(t('<strong>Accuracy is not reliability.</strong> PBE agreement, training stability, data independence and applicability are different questions. This exhibit keeps them separate.','<strong>Точность не равна надёжности.</strong> Согласие с PBE, устойчивость обучения, независимость данных и применимость — разные вопросы. Здесь они не смешиваются.'))
    main.append(sec('overview',overview))
    # 01 — molecule
    body=head(1,t('Geometry before metrics','Геометрия до метрик'),t('A proton between two oxygens.','Протон между двумя кислородами.'),t('Follow the nine saved PBE NEB images from one minimum to the other. The molecular scaffold changes as the proton moves.','Пройдите девять сохранённых PBE NEB-геометрий от одного минимума к другому. Вместе с протоном меняется и молекулярный остов.'))
    body+=f'''<div class="split molecule-layout"><figure class="panel molecule-panel"><div class="figure-meta"><span>{t('Exact image / display interpolation','Точный кадр / интерполяция')}</span><span id="mol-image-label">5 / 9</span></div><div id="molecule-view">{molecule_svg(d['molecule'][4]['xyz'])}</div><div class="controls js-only"><button id="mol-prev" aria-label="{t('Previous image','Предыдущий кадр')}">←</button><button id="mol-play" class="primary">{t('Play path','Воспроизвести')}</button><button id="mol-next" aria-label="{t('Next image','Следующий кадр')}">→</button><button id="mol-reset">{t('Reset','Сначала')}</button></div><div class="js-only"><label class="slider-label" for="mol-frame">{t('Saved image','Сохранённый кадр')}<input id="mol-frame" type="range" min="0" max="8" step="1" value="4"></label><label class="slider-label" for="mol-angle">{t('Viewing angle — display only','Ракурс — только отображение')}<input id="mol-angle" type="range" min="-50" max="50" value="0"></label></div><figcaption id="motion-note">{t('No physical clock. No new energies are calculated between images.','Без физического времени. Между кадрами новые энергии не вычисляются.')}</figcaption></figure><div><div class="panel"><h2>{t('One coordinate, two minima','Одна координата, два минимума')}</h2><p class="equation">q<sub>PT</sub> = r(O₁–H*) − r(O₂–H*)</p><p>{t('Negative: the proton is closer to O₁. Positive: closer to O₂. Near zero: similar O–H distances. O₁ and O₂ are fixed atom labels, not positions that change with the viewing angle.','Отрицательная: протон ближе к O₁. Положительная: ближе к O₂. Около нуля расстояния O–H близки. O₁ и O₂ — фиксированные номера атомов, не положения на экране.')}</p><div id="mol-metrics" class="metric-grid"></div></div><div class="panel chart-panel"><h3>{t('PBE energy along the saved path','Энергия PBE вдоль пути')}</h3>{chart('mol-energy')}<p class="small">{t('Energy relative to the lower endpoint. Lines are visual guides between computed points.','Энергия относительно нижнего endpoint. Линии лишь соединяют рассчитанные точки.')}</p></div></div></div>'''
    body+=fallback([t('Image','Кадр'),'qPT / Å','r(O₁–H*) / Å','r(O₂–H*) / Å','PBE / meV'],[[m['image'],f'{m["q"]:.6f}',f'{m["left"]:.6f}',f'{m["right"]:.6f}',f'{d["profiles"]["PBE"][i]:.6f}'] for i,m in enumerate(d['molecule'])],t('All nine saved geometries','Все девять сохранённых геометрий'))+source('path')+nextlink('sampling',t('Where should the model learn?','Где обучать модель?'))
    main.append(sec('molecule',body))
    # 02 — sampling
    body=head(2,t('Equal data budget','Равный бюджет данных'),t('Same sixty. Different coverage.','Те же шестьдесят. Другое покрытие.'),t('Keep the architecture and training settings fixed. Keep 36 shared configurations. Move the other 24 from the minima toward the transition region.','Архитектура и настройки обучения фиксированы. 36 конфигураций общие. Ещё 24 размещены у минимумов или в переходной области.'))
    body+=f'<div class="budget-row"><div><span>{t("Shared foundation","Общая основа")}</span><strong>36</strong></div><b>+</b><div><span>{t("Strategy-specific","По своей стратегии")}</span><strong>24</strong></div><b>=</b><div><span>{t("Per MTP model","На одну MTP-модель")}</span><strong>60</strong></div></div>'
    body+=f'<div class="panel"><div class="section-bar"><div><h2>{t("Where the training geometries lie","Где расположены обучающие геометрии")}</h2><p class="small">{t("A projection of real training configurations: qPT against O–O distance. Not a free-energy surface.","Проекция реальных обучающих конфигураций: qPT и расстояние O–O. Это не поверхность свободной энергии.")}</p></div><label class="js-only">{t("Show","Показать")}<select id="sampling-branch"><option value="both">{t("Both strategies","Обе стратегии")}</option><option value="basin">Basin60</option><option value="targeted">Targeted60</option></select></label></div>{chart("sampling-chart")}<div class="legend"><span class="shared">◆ {t("Shared 36","Общие 36")}</span><span class="basin">● Basin +24</span><span class="targeted">● Targeted +24</span></div></div>'
    body+=note(t('<strong>K = pool size = 24.</strong> Every transition candidate was selected. The experiment tests spatial allocation, not the ability of MaxVol to rank a smaller subset from a larger candidate pool.','<strong>K = размер пула = 24.</strong> Все переходные кандидаты отобраны. Эксперимент проверяет размещение данных, а не способность MaxVol выбрать лучшее подмножество большого пула.'))+source('train_basin','train_targeted','methods')+nextlink('landscape',t('What changed in the energy profile?','Как изменился энергетический профиль?'))
    main.append(sec('sampling',body))
    # 03 — energy
    body=head(3,t('The original locked pair','Исходная сохранённая пара'),t('Learning the barrier. Missing the shape.','Выучить барьер. Не потерять форму.'),t('Compare PBE with the two original 60-configuration MTPs on the same saved path. A small average error near a minimum is not a guarantee at the transition.','Сравните PBE и две исходные MTP на одном сохранённом пути. Малая ошибка у минимума не гарантирует точности в переходной области.'))
    body+=f'<div class="panel"><div class="section-bar"><h2>{t("Nine images, three profiles","Девять кадров, три профиля")}</h2><div class="controls js-only">'+''.join(f'<label class="check"><input type="checkbox" data-series="{k}" checked><span class="{k.lower()}">{k}</span></label>' for k in ['PBE','Basin60','Targeted60'])+'</div></div>'+chart('landscape-chart')+f'<label class="slider-label js-only" for="landscape-frame">{t("Inspect image","Выберите кадр")}<input id="landscape-frame" type="range" min="0" max="8" value="4"></label><div id="landscape-readout" class="readout" aria-live="polite"></div></div>'
    body+=table([t('Model','Модель'),t('Barrier / meV','Барьер / meV'),t('Barrier error / meV','Ошибка барьера / meV'),t('Central force RMSE / eV Å⁻¹','RMSE переходных сил / eV Å⁻¹')],[[k,f'{d["metrics"][k]["barrier"]:.6f}',f'{d["metrics"][k]["barrier_error"]:.6f}',f'{d["metrics"][k]["force_rmse"]:.6f}'] for k in ['PBE','Basin60','Targeted60']],t('Original model pair · smaller errors mean closer agreement with the PBE reference','Исходная пара · меньшие ошибки означают более близкое согласие с PBE'))
    body+=note(t('Each profile is referenced to its <strong>own lower endpoint</strong>. The discrete barrier is max(E) − min(E₁, E₉). Force RMSE uses the three central images, |qPT| ≤ 0.15 Å. Both endpoint geometries overlap training; the whole path is not an independent holdout.','Каждый профиль отсчитывается от <strong>своего нижнего endpoint</strong>. Дискретный барьер: max(E) − min(E₁, E₉). RMSE сил рассчитана по трём центральным кадрам, |qPT| ≤ 0,15 Å. Геометрии обоих концов есть в обучении: весь путь не является независимым holdout.'))+source('path','basin','targeted','methods')+nextlink('seeds',t('Does the advantage survive another initialization?','Сохранится ли преимущество при другом старте?'))
    main.append(sec('landscape',body))
    # 04 — seeds
    body=head(4,t('A robustness check','Проверка устойчивости'),t('Five seeds. A less simple answer.','Пять seeds. Менее простой ответ.'),t('All five paired trainings are shown, not just the best result. Switch the metric, then inspect one pair without hiding the others.','Показаны все пять пар обучений, а не лучший результат. Переключите метрику и выделите пару, не скрывая остальные.'))
    body+=f'<div class="split"><div class="panel"><div class="control-row js-only"><label>{t("Error metric","Метрика ошибки")}<select id="seed-metric"><option value="barrier">{t("Barrier error / meV","Ошибка барьера / meV")}</option><option value="force">{t("Transition force RMSE / eV Å⁻¹","RMSE сил / eV Å⁻¹")}</option></select></label><label>{t("Inspect pair","Выберите пару")}<select id="seed-select"><option value="all">{t("All five","Все пять")}</option>'+''.join(f'<option value="{i}">{i+1}</option>' for i in range(5))+'</select></label></div>'+chart('seed-chart')+f'<div class="legend"><span class="basin">● Basin60</span><span class="targeted">● Targeted60</span></div><p id="seed-readout" class="small" aria-live="polite"></p></div><aside class="panel editorial-panel"><p class="eyebrow">SEED_SENSITIVE</p><div class="stat-large">3 <em>/ 5</em></div><h2>'+t('Targeted wins both metrics.','Targeted лучше по обеим метрикам.')+'</h2><p>'+t('Four of five on the barrier. Three of five on transition forces. One pair reverses both metrics; another splits the outcome.','Четыре из пяти по барьеру. Три из пяти по переходным силам. Одна пара меняет знак преимущества по обеим метрикам, ещё одна даёт смешанный результат.')+'</p><p>'+t('These five pairs demonstrate sensitivity, not a reliable estimate of the chance of winning a future training run.','Пять пар показывают чувствительность, но не дают надёжной оценки вероятности выигрыша будущего обучения.')+'</p></aside></div>'
    body+=fallback([t('Pair','Пара'),t('Model','Модель'),'seed (uint64)',t('Barrier error / meV','Ошибка барьера / meV'),'RMSE / eV Å⁻¹'],[[r['index']+1,r['model'],r['seed'],f'{r["barrier"]:.6f}',f'{r["force"]:.6f}'] for r in d['seeds']],t('Exact seeds are stored as strings to preserve 64-bit identity','Seeds хранятся строками: 64-битные значения не округляются'))+note(t('The original run interleaved evaluation and training. A later evaluation-only repair reproduced all ten prediction files byte-for-byte. The historical nonconformance remains recorded; no best seed was selected.','Историческое исполнение чередовало обучение и оценку. Позднее отдельное исправляющее оценивание воспроизвело все десять файлов предсказаний побайтово. Нарушение порядка сохранено в истории; лучший seed не выбирался.'))+source('seeds','randomness','science')+nextlink('applicability',t('Now ask a different question: can it move?','Другой вопрос: можно ли запустить движение?'))
    main.append(sec('seeds',body))
    # 05 — applicability
    body=head(5,t('Two different diagnostics','Две разные диагностики'),t('A warning is not an error bar.','Предупреждение — не оценка ошибки.'),t('MaxVol gamma describes a query relative to an active basis. A PBE force error compares two force arrays. They are not interchangeable measurements.','Gamma MaxVol характеризует запрос относительно активного базиса. Ошибка сил по PBE сравнивает два массива сил. Это разные измерения.'))
    body+=f'<div class="concept-pair"><article><span class="eyebrow">01 / γ</span><h2>{t("Applicability / coverage","Применимость / покрытие")}</h2><p>{t("A selector-dependent algebraic diagnostic. It can trigger a frozen stopping rule; it is not a force error in eV/Å.","Алгебраическая диагностика, зависящая от селектора. Она может активировать правило остановки, но не является ошибкой сил в eV/Å.")}</p></article><article><span class="eyebrow">02 / ΔF</span><h2>{t("PBE-reference accuracy","Точность относительно PBE")}</h2><p>{t("A local measured discrepancy between MTP and saved PBE forces on the same geometry. It does not certify every later trajectory.","Локальное измеренное расхождение сил MTP и PBE на одной геометрии. Оно не подтверждает точность любой будущей траектории.")}</p></article></div>'
    body+=f'<div class="panel"><div class="section-bar"><div><h2>Replay228 · Train119</h2><p class="small">{t("Saved scores of the frozen force-aware selector; no new grading.","Сохранённые оценки фиксированного force-aware селектора; нового расчёта gamma нет.")}</p></div><label class="js-only">{t("Window","Окно")}<select id="gamma-window"><option value="all">{t("All 228","Все 228")}</option><option value="crossing">Crossing7 · 142–148</option><option value="challenge">Challenge4 · 93–96</option></select></label></div>{chart("gamma-chart")}<p class="small">{t("Frame index is an archive index, not a continuous physical time axis. Zoom changes the display, never the stopping threshold.","Индекс кадра — номер в архиве, не непрерывное физическое время. Масштаб меняет отображение, не порог остановки.")}</p></div>'
    body+=f'<div class="timeline"><div><span>Targeted60</span><p>{t("Six first attempted updates at 100, 300 and 500 K were rejected by the historical applicability threshold. No usable free MD trajectory resulted.","Шесть первых попытанных шагов при 100, 300 и 500 K отклонены историческим порогом применимости. Пригодной свободной MD-траектории не получено.")}</p></div><div><span>Tube92 → Train119</span><p>{t("Later adaptive work examined selector equations and local PBE errors. Those diagnoses do not retroactively clear the earlier gates.","Поздняя адаптивная работа исследовала уравнения селектора и локальные ошибки PBE. Она не отменяет ранее проваленные проверки.")}</p></div><div><span>Stage91J</span><p>{t("Five of 228 frames exceed 1.0000012996964838. The status remains STATIC_APPLICABILITY_FAIL.","Пять из 228 кадров превышают 1,0000012996964838. Статус остаётся STATIC_APPLICABILITY_FAIL.")}</p></div></div>'+source('replay','science','continuation')+nextlink('train119',t('Measure the forces on the rejected neighborhood','Измерить силы в отклонённой окрестности'))
    main.append(sec('applicability',body))
    # 06 — Train119
    body=head(6,t('October 5 diagnostic · published October 9','Диагностика 5 октября · опубликована 9 октября'),t('Small local errors.<br>An unchanged failure.','Малые локальные ошибки.<br>Неотменённый отказ.'),t('Examine eleven saved 100 K development frames. Crossing7 received seven historical PBE single points; Challenge4 reused four existing references. The Train119 model was unchanged.','Изучите одиннадцать сохранённых кадров разработки при 100 K. Для Crossing7 выполнены семь исторических PBE-расчётов; Challenge4 использует четыре прежних эталона. Модель Train119 не менялась.'))
    body+=f'<div class="section-bar"><span class="badge warning">STATIC_APPLICABILITY_FAIL</span><label class="js-only">{t("Inspect a frame","Выберите кадр")}<select id="case-frame">'+''.join(f'<option value="{r["replay_index"]}">{r["role"]} / {r["replay_index"]}</option>' for r in d['local'])+'</select></label></div>'
    body+=f'<div class="split"><figure class="panel"><h2>{t("Coverage score γ","Оценка покрытия γ")}</h2>{chart("case-gamma")}<figcaption>{t("Dimensionless. The dashed line is the unchanged numerical stop.","Безразмерная величина. Пунктир — неизменённый численный stop.")}</figcaption></figure><figure class="panel"><h2>{t("Force-component RMSE","RMSE компонент сил")}</h2>{chart("case-force")}<figcaption>{t("eV/Å. A2 is a bound on per-configuration RMSE, not on every component.","eV/Å. A2 ограничивает RMSE конфигурации, не каждую компоненту силы.")}</figcaption></figure></div><div id="case-readout" class="readout" aria-live="polite"></div>'
    body+=note(t('<strong>Two correlated segments, not eleven IID tests.</strong> Challenge4 frames 93–96 precede training additions 97–100. Replay228 was repeatedly used in development. Good local force errors do not justify loosening the historical stop.','<strong>Два коррелированных сегмента, не одиннадцать IID-тестов.</strong> Кадры Challenge4 93–96 предшествуют обучающим дополнениям 97–100. Replay228 неоднократно использовался при разработке. Малые локальные ошибки не разрешают ослаблять исторический stop.'))
    body+=fallback([t('Frame','Кадр'),t('Subset','Набор'),'γ',t('Force RMSE / eV Å⁻¹','RMSE сил / eV Å⁻¹'),t('Above stop','Выше stop')],[[r['replay_index'],r['role'],f'{r["gamma_saved"]:.9f}',f'{r["force_component_RMSE_eV_A"]:.9f}',t('Yes','Да') if r['above_stop'] else t('No','Нет')] for r in d['local']],t('All eleven local PBE comparisons','Все одиннадцать локальных сравнений с PBE'))
    body+=f'<div class="split section-gap"><div class="panel"><h2>{t("A separate development path check","Отдельная разработочная проверка пути")}</h2>{chart("case-energy")}<div class="legend"><span class="pbe">● PBE</span><span class="train119">● Train119</span></div></div><div class="panel editorial-panel"><p class="eyebrow">Audit21 · {t("Not an independent holdout","Не независимый holdout")}</p><div class="stat-large">{t("0.123","0,123")} <em>meV</em></div><h2>{t("Discrete barrier error","Ошибка дискретного барьера")}</h2><p>{t("Central-three-image force RMSE: 0.013834 eV/Å. Both NEB endpoints overlap training. A 119-configuration adaptive model is not another branch of the original equal-budget experiment.","RMSE сил трёх центральных кадров: 0,013834 eV/Å. Оба NEB endpoint пересекаются с обучением. Адаптивная модель на 119 конфигурациях — не третья ветка исходного equal-budget опыта.")}</p><p class="small">{t("The full profile is not accurate to 0.123 meV everywhere: its maximum own-endpoint-referenced error is about 0.504 meV.","Точность всего профиля не ограничена 0,123 meV: максимальная ошибка относительно собственного нижнего endpoint — около 0,504 meV.")}</p></div></div>'+source('diagnostic','train119','train119_prediction','geometry','roles','corrections')+nextlink('story',t('Watch the original visual chapters','Посмотреть исторические видеоглавы'))
    main.append(sec('train119',body))
    # 07 — media
    body=head(7,t('The visual archive','Визуальный архив'),t('The experiment, in motion.','Эксперимент в движении.'),t('Five original 60 fps films from the October 5 visual release. Preserved as historical media: Russian on-screen text, with English explanations below. The later local Train119 diagnosis is described in its own section.','Пять оригинальных роликов 60 fps из визуального релиза 5 октября. Сохранены как исторические материалы. Поздняя локальная диагностика Train119 вынесена в отдельный раздел.'))
    films=[('01_proton_path',t('One proton, two minima','Один протон, два минимума'),'34 s',t('Nine saved PBE NEB images. Smooth movement is a display interpolation; screen time is not reaction time.','Девять PBE NEB-геометрий. Плавное движение — интерполяция для показа; время экрана не является временем реакции.')),
    ('02_equal_budget',t('Where to place 24 points?','Куда поставить 24 точки?'),'46 s',t('The original equal-budget comparison, endpoint overlaps and all five paired seeds—not a best-run selection.','Исходное сравнение при равном бюджете, endpoint-пересечения и все пять пар seeds — без выбора лучшего запуска.')),
    ('03_applicability_boundary',t('A boundary we did not erase','Граница, которую не стёрли'),'40 s',t('Historical Stage91J closure. The later local PBE diagnostic does not promote the model to reactive dynamics.','Историческое закрытие Stage91J. Поздняя локальная проверка PBE не делает модель готовой к реакционной динамике.')),
    ('04_story_teaser',t('The story in twenty seconds','История за двадцать секунд'),'20 s',t('An editorial trailer of the original presentation; not a new physical calculation.','Редакционный тизер исходной презентации, не новый физический расчёт.')),
    ('05_proton_vertical',t('A closer, vertical view','Вертикальный взгляд на молекулу'),t('Vertical','Вертикальный'),t('The same saved path, composed for a portrait screen. The interpolation remains illustrative.','Тот же сохранённый путь в вертикальной композиции. Интерполяция остаётся иллюстративной.'))]
    body+='<div class="film-grid">'
    for i,(file,title,time,cap) in enumerate(films):
        body+=f'<figure class="film {"portrait" if i==4 else ""}"><div class="film-head"><span>0{i+1} / {time}</span><h2>{title}</h2></div><video controls playsinline preload="none" poster="assets/{file}_poster.jpg" aria-label="{e(title)}"><source src="media/{file}.mp4" type="video/mp4"></video><figcaption>{cap}</figcaption><div class="film-actions"><a href="media/{file}.mp4" download>{t("Download original MP4","Скачать оригинал MP4")} ↗</a><span class="video-state" role="status"></span></div></figure>'
    body+='</div>'+source('media','old_story')+nextlink('longread',t('Read the complete research story','Прочитать всю историю исследования'))
    main.append(sec('story',body))
    # 08 — longread
    body=head(8,t('The complete story','Полный рассказ'),t('Where should twenty-four<br>DFT points go?','Куда поставить<br>двадцать четыре DFT-точки?'),t('From a promising energy profile to a more careful account of what a machine potential knows. Updated with the bounded Train119 diagnostic.','От обнадёживающего энергетического профиля к более строгому пониманию возможностей машинного потенциала. С учётом локальной диагностики Train119.'))
    body+=f'<div class="article-meta"><span>{t("Mikhail Fofonov · research narrative","Михаил Фофонов · история исследования")}</span><a href="longread.{lang}.md" download>{t("Download text","Скачать текст")} ↓</a><button class="js-only" id="print-story">{t("Print / save as PDF","Печать / сохранить PDF")}</button></div><div class="reading-layout"><aside class="reading-aside"><p class="eyebrow">{t("Reading map","Карта чтения")}</p><div id="reading-toc"></div><p class="small">{t("Every chapter is tied to a frozen source. This is a revised editorial narrative, not a new physical experiment.","Каждая глава связана с источником. Это обновлённый рассказ, не новый физический эксперимент.")}</p></aside><article class="prose" id="longread-content">{article}</article></div>'
    body+=source('old_story','methods','randomness','continuation','diagnostic','corrections')+nextlink('reproduce',t('Go from the story to the evidence','От рассказа к доказательствам'))
    main.append(sec('longread',body))
    # 09 — reproducibility
    body=head(9,t('Open evidence, bounded claims','Открытые данные, ограниченные выводы'),t('Read it. Inspect it. Reproduce it.','Прочитать. Проверить. Воспроизвести.'),t('The site is a view of frozen public artifacts, not a live potential. Every plotted value can be traced back to a file and a SHA-256 hash.','Сайт отображает фиксированные публичные артефакты, а не рассчитывает потенциал. У каждого числа есть исходный файл и SHA-256.'))
    body+=f'<div class="split"><div class="panel"><h2>{t("Three checks, no new physics","Три проверки, без новой физики")}</h2><pre><code>git clone {REPO}.git\ncd malonaldehyde-transition-sampling\npython3 tools/run_public_selftests.py .\npython3 tools/verify_train119_diagnostic.py \\\n  --data data/post_publication/train119_diagnostic_v001\npython3 tools/build_research_site.py --out _site</code></pre><p class="small">{t("Python 3.11+; saved-data checks use the standard library. Building this site does not call QE, MLIP or LAMMPS.","Python 3.11+; проверки используют стандартную библиотеку. Сборка сайта не вызывает QE, MLIP или LAMMPS.")}</p><div class="actions"><a class="button primary" href="{REPO}">GitHub ↗</a><a class="button" href="data/science.json" download>JSON ↓</a><a class="button" href="build-manifest.json">SHA-256 ↗</a></div></div><aside class="panel"><p class="eyebrow">{t("The boundary of the claim","Граница утверждения")}</p><h2>{t("What this does not show","Чего здесь не доказано")}</h2><p>{t("No validated Train119 reactive MD, no prospective final holdout, no experimental accuracy, no universal gamma-to-error rule. PBE is an internal computational reference.","Нет валидированной реакционной MD Train119, перспективного финального holdout, экспериментальной точности или универсальной связи gamma с ошибкой. PBE — внутренний вычислительный эталон.")}</p><p>{t("Blind12 remains unrevealed. Historical scientific results, old media and release tags are preserved.","Blind12 остаётся закрытым. Исторические научные результаты, медиа и релизы сохранены.")}</p><div class="badges">{pill('SEED_SENSITIVE')}{pill('STATIC_APPLICABILITY_FAIL','warning')}</div></aside></div>'
    body+='<div class="section-gap"><h2>'+t('Source index','Указатель источников')+'</h2>'
    for k in d['evidence']:body+=source(k)
    body+=f'</div><div class="credits"><h2>{t("About this exhibit","Об этом сайте")}</h2><p>{t("Research: Mikhail Fofonov. Editorial and interactive presentation: October 2026. Same-series design reference: Memory / Geometry. Original scientific assets remain authoritative.","Исследование: Михаил Фофонов. Редакционная и интерактивная версия: октябрь 2026. Дизайн-референс серии: Memory / Geometry. Авторитетными остаются исходные научные артефакты.")}</p><p><a href="{REPO}/blob/main/CITATION.cff">{t("Citation metadata","Метаданные цитирования")}</a> · <a href="{REPO}/blob/main/docs/RESEARCH_SITE.md">{t("Build & licensing notes","Сборка и лицензирование")}</a> · <a href="https://spicmaff.github.io/rendezvous-grid-mazes/">Memory / Geometry ↗</a></p></div>'
    main.append(sec('reproduce',body))
    nav=''.join(f'<a href="#{id}" data-route="{id}">{name}</a>' for id,name in zip(SECTIONS,names))
    other='index.html' if ru else 'ru.html';langtext='EN' if ru else 'RU'
    title=t('One Proton, Two Ways to Learn — Malonaldehyde','Один протон, два способа обучения — Малональдегид')
    description=t('An interactive research story about proton transfer, equal-budget MTP sampling, training randomness and the limits of applicability.','Интерактивная история переноса протона: MTP, равный бюджет DFT, случайность обучения и границы применимости.')
    return f'''<!doctype html>
<html lang="{lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="description" content="{description}"><meta name="theme-color" content="#f5f3ec"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:image" content="https://spicmaff.github.io/malonaldehyde-transition-sampling/social-preview.png"><link rel="canonical" href="https://spicmaff.github.io/malonaldehyde-transition-sampling/{'ru.html' if ru else ''}"><link rel="alternate" hreflang="en" href="index.html"><link rel="alternate" hreflang="ru" href="ru.html"><title>{title}</title><link rel="icon" href="favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="style.css"><script type="module" src="app.mjs"></script></head><body><a class="skip" href="#main">{t('Skip to content','Перейти к содержимому')}</a><header><div class="wrap top"><a class="brand" href="#overview"><svg viewBox="0 0 40 28" aria-hidden="true"><path d="M7 20L13 7H27L33 20"/><path d="M7 20H33" stroke-dasharray="3 4"/><circle cx="7" cy="20" r="4"/><circle cx="33" cy="20" r="4"/><circle cx="20" cy="20" r="3"/></svg><span>PROTON / POTENTIAL</span></a><div class="top-tools"><a class="repository-link" href="{REPO}">GitHub ↗</a><a id="language" class="language" href="{other}#overview" lang="{'en' if ru else 'ru'}" aria-label="{t('Switch to Russian','Switch to English')}">{langtext}</a><button id="theme" class="theme js-only" aria-label="{t('Switch color theme','Переключить цветовую тему')}">◐ <span>{t('Dark','Тёмная')}</span></button></div></div><div class="wrap"><nav aria-label="{t('Research sections','Разделы исследования')}">{nav}</nav></div></header><main id="main" class="wrap" tabindex="-1"><noscript><p class="note">{t('The full story and numerical tables below work without JavaScript. Interactive controls require JavaScript; no account or external service is needed.','Полный рассказ и численные таблицы доступны без JavaScript. Для интерактивных элементов нужен JavaScript; аккаунт и внешний сервис не требуются.')}</p></noscript><div id="load-error" role="alert" hidden></div>{''.join(main)}</main><footer><div class="wrap footer-inner"><div>PROTON / POTENTIAL <span>·</span> {t('Mikhail Fofonov','Михаил Фофонов')}</div><div>{t('Science snapshot','Научный снимок')}: <a href="{REPO}/tree/{d['science_commit']}">{d['science_commit'][:7]}</a> · <a href="#reproduce">{t('Evidence & methods','Данные и методы')}</a></div></div></footer></body></html>'''
